*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 01:46:50 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 01:46:05
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 881d6c2af3d8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x55a68689d530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a68689d530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 2)
[pid: 7|app: 0|req: 1/1] 59.9.136.7 () {42 vars in 964 bytes} [Mon Oct 31 02:06:55 2022] GET / => generated 16351 bytes in 28 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 7|app: 0|req: 2/2] 59.9.136.7 () {42 vars in 916 bytes} [Mon Oct 31 02:06:55 2022] GET /favicon.ico => generated 1974 bytes in 4 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 1)
Mon Oct 31 02:08:39 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 02:08:39 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 02:49:31 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 02:48:49
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 67a2ad8700a6
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x564f61527530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x564f61527530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 2)
[pid: 9|app: 0|req: 1/1] 71.6.232.25 () {34 vars in 474 bytes} [Mon Oct 31 02:55:32 2022] GET / => generated 16351 bytes in 31 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 2/2] 183.136.225.35 () {34 vars in 448 bytes} [Mon Oct 31 03:05:15 2022] GET / => generated 16351 bytes in 3 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 3/3] 183.136.225.35 () {36 vars in 509 bytes} [Mon Oct 31 03:05:16 2022] GET / => generated 16351 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 9|app: 0|req: 4/4] 183.136.225.35 () {36 vars in 531 bytes} [Mon Oct 31 03:05:16 2022] GET /favicon.ico => generated 1977 bytes in 4 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /robots.txt
[pid: 9|app: 0|req: 5/5] 183.136.225.35 () {36 vars in 529 bytes} [Mon Oct 31 03:05:16 2022] GET /robots.txt => generated 1974 bytes in 3 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 6/6] 59.9.136.7 () {44 vars in 995 bytes} [Mon Oct 31 03:07:40 2022] GET / => generated 16351 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 7/7] 59.9.136.7 () {42 vars in 974 bytes} [Mon Oct 31 03:25:02 2022] GET /admin => generated 0 bytes in 0 msecs (HTTP/1.1 301) 4 headers in 145 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 8/8] 59.9.136.7 () {42 vars in 976 bytes} [Mon Oct 31 03:25:02 2022] GET /admin/ => generated 0 bytes in 12 msecs (HTTP/1.1 302) 8 headers in 301 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 9/9] 59.9.136.7 () {42 vars in 1013 bytes} [Mon Oct 31 03:25:02 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 28 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/oracle/base.py", line 232, in get_new_connection
    **conn_params,
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 407, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 377, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 404, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 214, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1138, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 505, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 422, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 420, in compile
    sql, params = vendor_impl(self, self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 128, in as_oracle
    return lookup.as_sql(compiler, connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 179, in as_sql
    rhs_sql = self.get_rhs_op(connection, rhs_sql)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/lookups.py", line 183, in get_rhs_op
    return connection.operators[self.lookup_name] % rhs
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/oracle/base.py", line 90, in __get__
    instance.cursor().close()
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/oracle/base.py", line 232, in get_new_connection
    **conn_params,
django.db.utils.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
[pid: 9|app: 0|req: 10/10] 59.9.136.7 () {52 vars in 1332 bytes} [Mon Oct 31 03:25:18 2022] POST /admin/login/?next=/admin/ => generated 281619 bytes in 94 msecs (HTTP/1.1 500) 5 headers in 157 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 11/11] 59.9.136.7 () {42 vars in 1089 bytes} [Mon Oct 31 03:26:12 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
Mon Oct 31 03:31:31 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Oct 31 03:31:31 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:23:35 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:22:46
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 2e38c387f428
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x55dbcd242530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55dbcd242530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 10, cores: 2)
[pid: 10|app: 0|req: 1/1] 59.9.136.7 () {42 vars in 1040 bytes} [Mon Oct 31 05:24:59 2022] GET / => generated 16351 bytes in 38 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 10|app: 0|req: 2/2] 59.9.136.7 () {42 vars in 1052 bytes} [Mon Oct 31 05:25:21 2022] GET /admin/ => generated 0 bytes in 14 msecs (HTTP/1.1 302) 8 headers in 301 bytes (1 switches on core 1)
[pid: 10|app: 0|req: 3/3] 59.9.136.7 () {42 vars in 1089 bytes} [Mon Oct 31 05:25:21 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 41 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 0)
[pid: 10|app: 0|req: 4/4] 59.9.136.7 () {44 vars in 1113 bytes} [Mon Oct 31 05:25:24 2022] GET /admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 8 headers in 301 bytes (1 switches on core 1)
[pid: 10|app: 0|req: 5/5] 59.9.136.7 () {44 vars in 1150 bytes} [Mon Oct 31 05:25:24 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
[pid: 10|app: 0|req: 6/6] 59.9.136.7 () {44 vars in 1113 bytes} [Mon Oct 31 05:25:25 2022] GET /admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 8 headers in 301 bytes (1 switches on core 0)
[pid: 10|app: 0|req: 7/7] 59.9.136.7 () {44 vars in 1150 bytes} [Mon Oct 31 05:25:25 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 0)
[pid: 10|app: 0|req: 8/8] 59.9.136.7 () {44 vars in 1113 bytes} [Mon Oct 31 05:25:26 2022] GET /admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 302) 8 headers in 301 bytes (1 switches on core 1)
[pid: 10|app: 0|req: 9/9] 59.9.136.7 () {44 vars in 1150 bytes} [Mon Oct 31 05:25:26 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 11 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
[pid: 10|app: 0|req: 10/10] 185.132.53.101 () {28 vars in 300 bytes} [Mon Oct 31 05:34:23 2022] GET / => generated 16351 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
Not Found: /GponForm/diag_Form
[pid: 10|app: 0|req: 11/11] 185.132.53.101 () {40 vars in 579 bytes} [Mon Oct 31 05:34:24 2022] POST /GponForm/diag_Form?images/ => generated 2007 bytes in 5 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /srv/docker-server
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (/srv/docker-server/apps.sock)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:37:51 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:22:46
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 2e38c387f428
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x56443c2e0390
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56443c2e0390 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 27, cores: 2)
Mon Oct 31 05:37:59 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:40:26 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:22:46
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 80c06ffd5af8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x55aacbb9e530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55aacbb9e530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 10, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /srv/docker-server
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (/srv/docker-server/apps.sock)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:42:14 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:22:46
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 80c06ffd5af8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x5581dd6c0390
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5581dd6c0390 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 26, cores: 2)
Mon Oct 31 05:42:22 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:45:35 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:44:44
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 62a56afdd771
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x555efc015530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x555efc015530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /srv/docker-server
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (/srv/docker-server/apps.sock)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:48:11 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:44:44
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 62a56afdd771
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x562fa330b390
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x562fa330b390 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 27, cores: 2)
Mon Oct 31 05:48:19 2022 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Mon Oct 31 05:51:36 2022] ***
compiled with version: 6.3.0 20170516 on 31 October 2022 05:50:44
os: Linux-5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
nodename: 2b1d8b7937f8
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /srv/docker-server
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /srv/docker-server
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /srv/docker-server/apps.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.7 (default, Nov 16 2018, 22:33:19)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x556d5188b530
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166752 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556d5188b530 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 2)
[pid: 9|app: 0|req: 1/1] 59.9.136.7 () {46 vars in 1181 bytes} [Mon Oct 31 06:01:30 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 76 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 2/2] 59.9.136.7 () {46 vars in 1181 bytes} [Mon Oct 31 06:01:30 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 3/3] 59.9.136.7 () {46 vars in 1181 bytes} [Mon Oct 31 06:01:30 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 12 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 4/4] 59.9.136.7 () {46 vars in 1181 bytes} [Mon Oct 31 06:01:31 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 11 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 5/5] 59.9.136.7 () {46 vars in 1181 bytes} [Mon Oct 31 06:01:31 2022] GET /admin/login/?next=/admin/ => generated 1913 bytes in 11 msecs (HTTP/1.1 200) 8 headers in 431 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 6/6] 188.166.117.97 () {38 vars in 494 bytes} [Mon Oct 31 06:09:13 2022] GET / => generated 16351 bytes in 4 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 7/7] 59.9.136.7 () {52 vars in 1332 bytes} [Mon Oct 31 06:10:24 2022] POST /admin/login/?next=/admin/ => generated 0 bytes in 260 msecs (HTTP/1.1 302) 10 headers in 595 bytes (1 switches on core 0)
[pid: 9|app: 0|req: 8/8] 59.9.136.7 () {46 vars in 1188 bytes} [Mon Oct 31 06:10:24 2022] GET /admin/ => generated 3042 bytes in 93 msecs (HTTP/1.1 200) 7 headers in 263 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 9/9] 205.210.31.8 () {30 vars in 576 bytes} [Mon Oct 31 06:35:45 2022] GET / => generated 16351 bytes in 2 msecs (HTTP/1.0 200) 4 headers in 123 bytes (1 switches on core 0)
